FROM alpine:3.10.2
LABEL maintainer="github.com/satandyh" \
  name="openvas-docker" \
  version="0.1" \
  release="1.0" \
  architecture="x86-64" \
  vendor="Alpine"

# install gvmd and all dependencies
RUN echo http://dl-cdn.alpinelinux.org/alpine/edge/community >>/etc/apk/repositories && \
  apk --update add --no-cache gvmd

# copy config
COPY ./config/gvmd /etc/sysconfig/gvmd

# create user node
RUN addgroup -g 2000 node
RUN adduser -u 2000 -G node -s /bin/sh -D node
# run from user node
USER node

# Entrypoint
COPY ./entrypoint/gvmd_docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

# Start point
COPY ./run/gvmd_run.sh /usr/local/bin/run.sh
RUN chmod +x /usr/local/bin/run.sh
CMD ["/usr/local/bin/run.sh"]
#CMD ["gvmd", "-f", "-v", "--listen=0.0.0.0", "--port=9390"]

VOLUME ["/usr/local/var/lib/gvm"]

# export gvmd ports
EXPOSE 9390
